### ISSUE TITLE
OpenGL memory leak when minimizing/restoring window

### ISSUE THREAD

**Issue by nikitar020** [jumptrading/aminal#37]
**Describe the bug**
It looks like OpenGL memory is leaking when the Aminal' window is restoring from minimized state.

**To Reproduce**
1. Run Aminal
2. Run Task Manager and note current Aminal memory usage
3. Try to minimize and restore the window several times
4. On each restoration of the window, the memory consumption increases by 4 to 6 MB.

**Expected behavior**
There should be no increase in memory usage when minimizing/restoring the Aminal's window.

**Environment (please complete the following information):**
 - OS + Version: `Windows`

**Comment by MaxRis** [comment]
Moved to https://github.com/liamg/aminal/issues/129
