### ISSUE TITLE
Mosh support

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/aminal#6]
**Is your feature request related to a problem? Please describe.**
Integration with Mosh

**Describe the solution you'd like**
Cross-platform GoLang API to wrap Mosh https://mosh.org/#getting

**Comment by MaxRis** [comment]
Copy of comments from original discussion:

Alex:
See https://github.com/mobile-shell/mosh/issues/989 / https://gist.github.com/tkon99/7ea5202819ef026d66e484bcc2469d2b

Also https://github.com/mobile-shell/mosh/issues/293

I'm a little unsure if its best to bite the bullet and implement the bits requires for a Windows client in Go, or make the C++ that works on Linux/Mac work for Windows. 

Nikita:
Does Mosh really need to be native-implemented in aminal?... instead, shouldn't Mosh be a stand-alone application that can run in aminal or even be launched from cmd?

Alex:
no, it does not - it may well be a different code base/binary. It just needs to work well together. AT the same time, on the mosh github, there is a lot of talk of making it part of putty

**Comment by MaxRis** [comment]
@nikitar020 do we not need this anymore since you have closed the issue?

**Comment by nikitar020** [comment]
In my opinion, this functionality is not necessary in Aminal. I already posted that, and there are no objections so far...

**Comment by MaxRis** [comment]
@nikitar020 I'm going to re-open this Issue just to have the active record to track that we need this functionality and working progress on verifying that.

**Comment by MaxRis** [comment]
@nikitar020 the issue is moved to https://github.com/liamg/aminal/issues/128
